# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-03-12 03:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peopleinfo',
            old_name='book_id',
            new_name='book',
        ),
    ]
