# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-04-27 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210312_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='is_delete',
            field=models.BooleanField(default=True),
        ),
    ]
